### ISSUE TITLE
License file is MIT but license field says BSD3

### ISSUE THREAD

**Issue by juhp** [yav/monadlib#11]
See https://bugzilla.redhat.com/show_bug.cgi?id=2296801#c3

While reviewing this package for Fedora (as part of bring Copilot to Fedora),
it was noticed that monadLib has inconsistent license data:

- LICENSE file is MIT
- .cabal file license field says: BSD3

Could you help to clarify which is the correct license?

**Comment by yav** [comment]
@juhp I've just pushed a change that sets the license to ISC in both the cabal file and the license text (and fixed some cabal warning).   Do you need me to upload a new version to hackage?

**Comment by juhp** [comment]
Yes please that would be helpful, thank you

**Comment by juhp** [comment]
(Btw it would be nice to fix the [homepage](https://github.com/yav/monadlib/blob/master/monadLib.cabal#L8) link too while you are at it)

**Comment by fdedden** [comment]
Thanks a lot @yav! A new release to hackage would really help, so that the license is consistent in the future. This will help other packages as well.

**Comment by yav** [comment]
OK, should be available as version 3.10.3
