### ISSUE TITLE
Build failing in 8.8 due to MonadFail proposal

### ISSUE THREAD

**Issue by dpwiz** [yav/monadlib#5]
This happened:

> As part of the MonadFail proposal (MFP), this function is moved
> to its own class 'MonadFail' (see "Control.Monad.Fail" for more
> details). The definition here will be removed in a future
> release.

And instances like this do not work anymore:

```haskell
instance Monad (Reader i) where
  return  = derive_return iso_R
  fail    = derive_fail iso_R
  (>>=)   = derive_bind iso_R
```

```
monadLib>     ‘fail’ is not a (visible) method of class ‘Monad’
```

**Comment by yav** [comment]
Thanks for reporting this, it should be fixed now with version 3.10
