### ISSUE TITLE
Move `return` derivations to Applicative instances

### ISSUE THREAD

**Issue by dpwiz** [yav/monadlib#6]
In preparations for [Monad-of-no-return](https://gitlab.haskell.org/ghc/ghc/wikis/proposal/monad-of-no-return).

`base >= 4.8` (ghc 7.10) got the default implementation of `return` pointing to it. Explicit `return = pure` definition could be left under `#if __GLASGOW_HASKELL__ < 710`.

**Comment by yav** [comment]
Thanks, this should be done now with version 3.10
